spring:
  application:
    name: daemon
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    url: jdbc:sqlite:tracesentry.db
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
server:
  port: 8087