spring:
  application:
    name: daemon
  datasource:
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
server:
  port: 8087
ai:
  openai_endpoint: "https://api.openai.com/v1/chat/completions"

monitoring-scheduler:
  snapshot:
    interval: 60