#!/bin/bash

# check if the first argument is empty
if [ $# -eq 0 ]; then
    java -Dlogging.level.root=OFF -Dspring.profiles.active=dev -jar "$TRACE_SENTRY_DIR/bin/cli.jar"
else
    java -Dlogging.level.root=OFF -jar "$TRACE_SENTRY_DIR/bin/cli.jar" "$@"
fi

# todo: update instructions in report in german
# todo: where is db created?
# todo: check @reboot
